import type { Metadata } from "next";

import "./globals.css";
import Navbar from "./Components/Navbar"




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<head>

<style>

@import url('https://fonts.googleapis.com/css2?family=Chokokutai&display=swap');
</style>

</head>



      <body
        className={``}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
